version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/paintweb
    ports:
      - "8000:8000"
    stdin_open: true
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=paintweb.settings.development
      - PORT=8000

  db:
    image: postgres:11.1-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5