version: '3.8'

services:
  web:
    build: ./
#      context: ./paintweb
#      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/paintweb
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=paintweb
      - POSTGRES_PASSWORD=paintweb
      - POSTGRES_DB=paintweb_dev

volumes:
  postgres_data: