# Generated by Django 4.0.4 on 2022-05-27 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paintsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Designation')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='SubTag',
            fields=[
            ],
            options={
                'verbose_name': 'Sub tag',
                'verbose_name_plural': 'Sub tags',
                'ordering': ('super_tag__order', 'super_tag__name', 'order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paintsite.tag',),
        ),
        migrations.CreateModel(
            name='SuperTag',
            fields=[
            ],
            options={
                'verbose_name': 'Super tag',
                'verbose_name_plural': 'Super tags',
                'ordering': ('order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paintsite.tag',),
        ),
        migrations.AddField(
            model_name='tag',
            name='super_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='paintsite.supertag', verbose_name='Super tag'),
        ),
    ]
