# Generated by Django 4.0.4 on 2022-05-27 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import paintsite.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('paintsite', '0002_tag_subtag_supertag_tag_super_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Picture name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to=paintsite.utilities.get_timestamp_path, verbose_name='Picture')),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='Show in gallery?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Picture author')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paintsite.subtag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
                'ordering': ['-created_at'],
            },
        ),
    ]
