# Generated by Django 4.0.4 on 2022-05-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintsite', '0003_pictureboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureboard',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
