# Generated by Django 4.0.5 on 2022-06-12 09:52

from django.db import migrations, models
import paintsite.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('paintsite', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureboard',
            name='picture_url',
            field=models.URLField(default='https://www.salonlfc.com/en/image-not-found/', verbose_name='Picture url'),
        ),
        migrations.AlterField(
            model_name='pictureboard',
            name='image',
            field=models.ImageField(blank=True, upload_to=paintsite.utilities.get_timestamp_path, verbose_name='Picture'),
        ),
    ]
