# Generated by Django 4.0.5 on 2022-06-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintsite', '0006_pictureboard_picture_url_alter_pictureboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureboard',
            name='picture_url',
            field=models.URLField(default='https://www.salonlfc.com/en/image-not-found/', max_length=500, verbose_name='Picture url'),
        ),
    ]
