name: Test
on:
  push:
    branches: [main, compose]
jobs:
  testing:
    runs-on: ubuntu-latest
    environment: PaintWeb
    strategy:
      matrix:
        python-version: [ '3.8.10' ]
    env:
      working-directory: ./

    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_DATABASE_USER: ${{ secrets.DATABASE_USER }}
          envkey_DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
          envkey_EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          envkey_EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          envkey_EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          envkey_EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          envkey_EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
          envkey_PRODUCTION_HOST: ${{ secrets.PRODUCTION_HOST }}
          envkey_SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
          envkey_SQL_HOST: ${{ secrets.SQL_HOST }}
          directory: paintweb/settings
          file_name: .env
          fail_on_empty: true
      - name: Build-Up docker compose
        run: docker compose up -d --build
      - name: Testing
        run: docker compose exec web python3 manage.py test
